### PR TITLE
Added an initial, simple implementation of the grid

### PR DESCRIPTION
**Pull request by janthonysantana**
Image found in project Drive folder

### CODE REVIEW

**Comment by yumidev** [comment]
I think we should add the static images to repo.

**Comment by yumidev** [comment]
your branch doesn't have the latest changes from `dev` branch. You can either merge dev branch or rebase your branch to dev. 

https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by yumidev** [comment]
But these are not blockers and the PR looks good to me!

**Comment by janthonysantana** [comment]
> I think we should add the static images to repo.

I avoiding adding the one that I use for testing as I don't know if it's copyrighted or things like that

**Pull request merged**
